import NavBar from "@/components/NavBar";
import { getCompletion } from "@/utils/api/gpt4";
import { Box, TextField, Button, Typography } from "@mui/material";
import Head from "next/head";
import { useState } from "react";

export default function Chat() {
    const [sessionId, setSessionId] = useState(-1);
    const [sessionMessages, setSessionMessages] = useState([]);
    const [userInput, setUserInput] = useState("");

    const handleSendChat = async () => {
        let userMessage = userInput;
        let response = await getCompletion(userMessage, sessionId);
        if (sessionId == -1) {
            setSessionId(response.sessionId);
        }
        console.log(response);
        setSessionMessages((sessionMessages) => {
            return [
                ...sessionMessages,
                { role: "user", message: userMessage },
                { role: "assistant", message: response.response },
            ];
        });
        setUserInput("");
    };

    return (
        <>
            <Head>
                <title>Chat</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <NavBar />
            <Box height={100}>
                <h1 style={{ textAlign: "center", marginTop: "5rem" }}>Test</h1>

                {sessionMessages && sessionMessages.length > 0 && (
                    <Box
                        sx={{
                            width: "70%",
                            marginX: "auto",
                            padding: "1rem",
                            border: "1px solid",
                            borderRadius: "0.25rem",
                        }}
                    >
                        {sessionMessages.map((sessionMessage) => {
                            return (
                                <div style={{marginTop: "0.5rem"}}>
                                    <Typography>
                                        {sessionMessage.role}: {sessionMessage.message}
                                    </Typography>
                                </div>
                            );
                        })}
                    </Box>
                )}

                <div style={{ display: "flex", justifyContent: "center" }}>
                    <TextField
                        value={userInput}
                        onChange={(event) => setUserInput(event.target.value)}
                        multiline
                        sx={{ width: "70%" }}
                    />
                </div>
                <div style={{ display: "flex", justifyContent: "center" }}>
                    <Button onClick={async () => await handleSendChat()} sx={{ display: "block" }}>
                        Send
                    </Button>
                </div>
            </Box>
        </>
    );
}
