import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useEffect } from "react";
import { getCompletion } from "@/utils/api/gpt4";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
    useEffect(() => {
        (async () => {
            let response = await getCompletion("Tell me something cool");
            console.log(response.response);
        })();
    }, []);

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
                <main className={`${styles.main} ${inter.className}`}>
                    <div>
                        <h1>Serene Script</h1>
                    </div>
                </main>

        </>
    );
}
