import NavBar from "@/components/NavBar"
import Head from "next/head";
import { Box } from "@mui/material";

export default function ToDo() 
{
    return <>
            <Head>
                <title>ToDo</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <NavBar/>
            <Box>
                <h1>To Do</h1>
            </Box>
    </>
}