import NavBar from "@/components/NavBar"
import Head from "next/head";
import ToDoList from "@/components/ToDoList";

export default function ToDo() {
    
    return <div style={{
        width: "100vw",
        height: "100vh",
        backgroundImage: 'url("/landscape-background.webp")',
        backgroundSize: 'cover'
    }}>
            <Head>
                <title>ToDo</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <NavBar/>   
            <ToDoList/>
    </div>
}