import NavBar from "@/components/NavBar";
import Head from "next/head";
import ToDoList from "@/components/ToDoList";
import Background from "@/components/Background";

export default function ToDo() {
    return (
        <Background>
            <Head>
                <title>ToDo</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <NavBar />
            <ToDoList />
        </Background>
    );
}
